linters-settings:
  golint:
    min-confidence: 0

linters:
  enable:
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

run:
  timeout: 1m
